server {
    listen 80;
    server_name pos.devflix.uz;
    root /usr/share/nginx/html;
    index index.html;

    # Frontend SPA — API alohida domen: posapi.devflix.uz
    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}
